# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0058_processrun_rto'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='recover_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='恢复结束时间'),
        ),
    ]
