# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0061_processrun_log_restore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='log_restore',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=1, null=True, verbose_name='是否回滚日志'),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='log_restore',
            field=models.IntegerField(default=1, null=True, verbose_name='是否回滚日志'),
        ),
    ]
