# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0062_auto_20200324_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Process', verbose_name='流程预案')),
            ],
        ),
    ]
